CREATE TABLE CHANNELS(
        ID             SERIAL PRIMARY KEY,
        NAME           TEXT      NOT NULL,
        YTID           TEXT      NOT NULL,
        ISTUTS         BOOLEAN   NOT NULL
);

INSERT INTO CHANNELS (NAME, YTID, ISTUTS) VALUES ('Google Developers', 'UC_x5XG1OV2P6uZZ5FSM9Ttw', false);
INSERT INTO CHANNELS (NAME, YTID, ISTUTS) VALUES ('Android Developers', 'UCVHFbqXqoYvEWM1Ddxl0QDg', false);
INSERT INTO CHANNELS (NAME, YTID, ISTUTS) VALUES ('Docker', 'UC76AVf2JkrwjxNKMuPpscHQ', false);
INSERT INTO CHANNELS (NAME, YTID, ISTUTS) VALUES ('Team BDXIO', 'UCA7pEYY0BlgCdpbnjhCDezQ', false);
INSERT INTO CHANNELS (NAME, YTID, ISTUTS) VALUES ('Cloudera, Inc.', 'UCXY5wm6HlBL_Y_8SDxJNR0g', false);
INSERT INTO CHANNELS (NAME, YTID, ISTUTS) VALUES ('CoreOS', 'UCGORzzCxacx2r_NsF6_DteQ', false);
INSERT INTO CHANNELS (NAME, YTID, ISTUTS) VALUES ('dot conferences', 'UCSRhwaM00ay0fasnsw6EXKA', false);
INSERT INTO CHANNELS (NAME, YTID, ISTUTS) VALUES ('GDG France', 'UCx83f-KzDd3o1QK2AdJIftg', false);
INSERT INTO CHANNELS (NAME, YTID, ISTUTS) VALUES ('GDG Paris', 'UCGJGgXpgWR5H88gLStMzW8A', false);
INSERT INTO CHANNELS (NAME, YTID, ISTUTS) VALUES ('Google Cloud Platform', 'UCJS9pqu9BzkAMNTmzNMNhvg', false);
INSERT INTO CHANNELS (NAME, YTID, ISTUTS) VALUES ('ng-conf', 'UCm9iiIfgmVODUJxINecHQkA', false);
INSERT INTO CHANNELS (NAME, YTID, ISTUTS) VALUES ('ng-europe', 'UCEGUP3TJJfMsEM_1y8iviSQ', false);
INSERT INTO CHANNELS (NAME, YTID, ISTUTS) VALUES ('OReilly', 'UC3BGlwmI-Vk6PWyMt15dKGw', false);
INSERT INTO CHANNELS (NAME, YTID, ISTUTS) VALUES ('OpenStack Foundation', 'UCQ74G2gKXdpwZkXEsclzcrA', false);
INSERT INTO CHANNELS (NAME, YTID, ISTUTS) VALUES ('PuppetLabsInc', 'UCPfMWIY-qNbLhIrbZm2BFMQ', false);
INSERT INTO CHANNELS (NAME, YTID, ISTUTS) VALUES ('Rackspace', 'UCG0VI_ayS-I0RQpBna4Tisw', false);
INSERT INTO CHANNELS (NAME, YTID, ISTUTS) VALUES ('Rackspace Developers', 'UCgA-Xa2Q3ME90cQhZBNxNNw', false);
INSERT INTO CHANNELS (NAME, YTID, ISTUTS) VALUES ('The Go Programming Language', 'UCO3LEtymiLrgvpb59cNsb8A', false);
INSERT INTO CHANNELS (NAME, YTID, ISTUTS) VALUES ('vaadin official', 'UCsGakFIbOsj-fgPFLf1QlQA', false);
INSERT INTO CHANNELS (NAME, YTID, ISTUTS) VALUES ('D-Conf', 'UCaYYN56VR7Z4SSoO7ws0-jA', false);
INSERT INTO CHANNELS (NAME, YTID, ISTUTS) VALUES ('Andrei Alexandrescu', 'UCzYzlIaxNosNLAueoQaQYXw', false);
INSERT INTO CHANNELS (NAME, YTID, ISTUTS) VALUES ('MeetingCPP', 'UCJpMLydEYA08vusDkq3FmjQ', false);
INSERT INTO CHANNELS (NAME, YTID, ISTUTS) VALUES ('Javaone', 'UCmRtPmgnQ04CMUpSUqPfhxQ', false);
INSERT INTO CHANNELS (NAME, YTID, ISTUTS) VALUES ('Twitter University', 'UCeDh9omC_xMKrar2srQZiLg', false);
INSERT INTO CHANNELS (NAME, YTID, ISTUTS) VALUES ('Facebook Developers', 'UCP_lo1MFyx5IXDeD9s_6nUw', false);
INSERT INTO CHANNELS (NAME, YTID, ISTUTS) VALUES ('Black Hat', 'UCJ6q9Ie29ajGqKApbLqfBOg', false);
INSERT INTO CHANNELS (NAME, YTID, ISTUTS) VALUES ('BreizhJUG', 'UCVlyyvH7PK5NT6ZdCGS3zVQ', false);
INSERT INTO CHANNELS (NAME, YTID, ISTUTS) VALUES ('HTML5DevConf & IoTaconf', 'UC__NR52nzDsbmy2y0S13JIQ', false);
INSERT INTO CHANNELS (NAME, YTID, ISTUTS) VALUES ('Codegram Technologies', 'UCwoOpKfkyCQHW562hXXQAGg', false);
INSERT INTO CHANNELS (NAME, YTID, ISTUTS) VALUES ('JSConf', 'UCzoVCacndDCfGDf41P-z0iA', false);
INSERT INTO CHANNELS (NAME, YTID, ISTUTS) VALUES ('GoogleTechTalks', 'UCtXKDgv1AVoG88PLl8nGXmw', false);
INSERT INTO CHANNELS (NAME, YTID, ISTUTS) VALUES ('Confreaks', 'UCWnPjmqvljcafA0z2U1fwKQ', false);
